### ISSUE TITLE
replace docker with singularity 

### ISSUE THREAD

**Issue by JWinawer** [WinawerLab/SampleData#10]
this requires figuring out where singularity stores containers, and also checking whether the syntax for singularity calls is the same as docker calls. it also means updating our software page to add singularity as a dependency and remove docker.

**Comment by JWinawer** [comment]
CBI has a function called singpull:

```
#!/bin/bash

umask u=rwx,g=rx,o=rx
export SINGULARITY_CACHEDIR=/scratch/work/cbi/.singularity
cd ~/singularity
source=${1%/*}
[ ${#source} -gt 0 ] && mkdir -p $source && cd $source
singularity pull docker://${1}
```

**Comment by JWinawer** [comment]
Note that at least scripts have docker calls that need to be replaced with singularity: 

S1 (lots)
S2 (bidsValidation)
s4a 
S5 (neuropythy)

**Comment by JWinawer** [comment]
We think that we want to do this when we are on the cluster but not on local machines, since Mac OS does not work well with singularity.

**Comment by billbrod** [comment]
For now, we check if  `[[ $CLUSTER == "GREENE" ]]` and, if so, use singularity. Else, use docker.

Another way to do this is to automatically determine which to use by checking if we can use docker (if user is in `sudo` or `docker` groups) and, if not, use singularity.

Want to also allow for an argument / flag to specify which to use.

**Comment by JWinawer** [comment]
TODO: 
- [x]  Write a function called container_run in the file subroutines/utils.sh and replace calls like docker run blah with container_run blah
- [ ] Look for other places in scripts that call docker pull and replace with container_pull

**Comment by billbrod** [comment]
And also:
- [x] Test `container_pull` works for singularity (on Jon's local machine, raises a fatal error if image already exists, want to make sure that it runs successfully on container; one possibliity would be to add `-F` flag to the pull, which forces it to redownload the image)

**Comment by JWinawer** [comment]
We decided to keep docker for local machines and use singularity on the cluster.
