### ISSUE TITLE
benson atlases

### ISSUE THREAD

**Issue by JWinawer** [WinawerLab/SampleData#6]
Currently the Benson atlas (s5) operates on the output of what is now called s4b (analyzePRF). We would like it to operate on the output of s4a (vistaPRF). Or perhaps have one of each, s5a and s5b.

**Comment by jankurzawski** [comment]
We can now use aPRF or vista to run Noah's atlas. I vote for keeping vistasoft only for simplicity

**Comment by JWinawer** [comment]
See related issue #14
