### ISSUE TITLE
Make code run on cluster (s0)

### ISSUE THREAD

**Issue by JWinawer** [WinawerLab/SampleData#8]
s0 downloads the data. For now, it downloads it to a folder inside the folder containing the code. On the cluster, we would want the code to live in our home directory, and the data to live in scratch. So we need to fix either setup.sh or s0...

**Comment by billbrod** [comment]
Thought we found a solution for this in #15, but `set -e` at the top of our scripts means we can't use anything that returns a non-zero error code (we had been seeing if `module list` ran successfully).
